name: InSigns
main: de.blablubbabc.insigns.InSigns
version: 2.1
author: blablubbabc
description: Displays the text on signs for each player individual differently.
depend: [ProtocolLib]
permissions:
  insigns.create.player:
    description: Ability to create signs displaying individual player names.
    default: true