name: InSigns
main: de.blablubbabc.insigns.InSigns
version: '${version}'
author: ${authorAlias}
description: Displays the text on signs for each player individual differently.
depend: [ProtocolLib]
permissions:
  insigns.create.player:
    description: Ability to create signs displaying individual player names.
    default: true
  insigns.create.display:
    description: Ability to create signs displaying individual player display/nick names.
    default: true